### ISSUE TITLE
ImportError: cannot import name Templar

### ISSUE THREAD

**Issue by rabin-io** [fabriziopandini/vagrant-compose#14]
With this simple setup I get the above error message

```ruby
# Vagrantfile
Vagrant.configure("2") do |config|

    # Verify whether required plugins are installed.
    required_plugins = [ "vagrant-hostmanager" , "vagrant-compose" ]
    required_plugins.each do |plugin|
        if not Vagrant.has_plugin?(plugin)
            raise "The vagrant plugin #{plugin} is required. Please run `vagrant plugin install #{plugin}`"
        end
    end

    config.cluster.from("setup.yaml")

    #cluster creation
    config.cluster.nodes.each do |node, index|
        config.vm.define "#{node.boxname}" do |node_vm|
            node_vm.vm.box = "#{node.box}"
        end
    end
```

```yaml
---
# setup.yaml
kubernetes:
  master:
    instances: 1
  minions:
    instances: 3
```

Traceback
```
Error running cluster playbook:
Traceback (most recent call last):
  File "/usr/bin/vagrant-playbook", line 11, in <module>
    load_entry_point('vagrant-playbook==0.7.2', 'console_scripts', 'vagrant-playbook')()
  File "/usr/lib/python2.7/site-packages/vagrantplaybook/__main__.py", line 22, in main
    from vagrantplaybook.playbook.executor import Executor
  File "/usr/lib/python2.7/site-packages/vagrantplaybook/playbook/executor.py", line 9, in <module>
    from vagrantplaybook.ansible import ansible_unwrap, ansible_loader
  File "/usr/lib/python2.7/site-packages/vagrantplaybook/ansible.py", line 6, in <module>
    from ansible.template import Templar
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 47, in <module>
    from ansible.vars.unsafe_proxy import UnsafeProxy, wrap_var
  File "/usr/lib/vagrant-hostmanager (1.8.5, system)python2.7/site-packages/ansible/vars/__init__.py", line 42, in <module>
    from ansible.template import Templar
ImportError: cannot import name Templar
```

* running on Fedora26
* vagrant-playbook (0.7.2)
* vagrant-compose (0.7.4)
* vagrant-hostmanager (1.8.5, system)
* vagrant-libvirt (0.0.37, system)

**Comment by fabriziopandini** [comment]
@rabin-io thanks for reporting the problem. Could you kindly  tell me wich version of ansible are you using?

**Comment by rabin-io** [comment]
Hay @fabriziopandini i'm using ansible from Fedora repo
current version is: 
```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

**Comment by fabriziopandini** [comment]
@rabin-io your configuration works fine on my setup. I will try to reproduce your setup ASAP.

In the meantime, could you kindly run `vagrant-playbook -f setup.yaml` this will hopefully provide a more clear stack trace, because the current one has something that is a little bit confusing so far:

1) it seems that ansible is properly invoked, but then the problem happen somewhere inside ansible:
  ...
  File "/usr/lib/python2.7/site-packages/**ansible/template/__init__.py**", line 47, in <module>
    from ansible.vars.unsafe_proxy import UnsafeProxy, wrap_var
  File "/usr/lib/vagrant-hostmanager (1.8.5, system)python2.7/site-packages/**ansible/vars/__init__.py**", line 42, in <module>
    from ansible.template import Templar

2)  it seems that ansible, when invoked, is mixing two different versions of ansible
  ...
  File "/usr/lib/**python2.7/site-packages/ansible**/template/__init__.py", line 47, in <module>
    from ansible.vars.unsafe_proxy import UnsafeProxy, wrap_var
  File "/usr/lib/**vagrant-hostmanager (1.8.5, system)python2.7/site-packages**/ansible/vars/__init__.py", line 42, in <module>
    from ansible.template import Templar

**Comment by rabin-io** [comment]
@fabriziopandini one more note, my provisioning playbook is under `provisioning/playbook.yml` but i removed it from the Vagrantfile to bare minimal because i want to change it to use the ` Declarative Approach` and even with the bare minimal it didn't work for me.

running `vagrant-playbook` with `setup.yaml` produce the same TB
```
vagrant-playbook -f setup.yaml

Traceback (most recent call last):
  File "/usr/bin/vagrant-playbook", line 11, in <module>
    load_entry_point('vagrant-playbook==0.7.2', 'console_scripts', 'vagrant-playbook')()
  File "/usr/lib/python2.7/site-packages/vagrantplaybook/__main__.py", line 22, in main
    from vagrantplaybook.playbook.executor import Executor
  File "/usr/lib/python2.7/site-packages/vagrantplaybook/playbook/executor.py", line 9, in <module>
    from vagrantplaybook.ansible import ansible_unwrap, ansible_loader
  File "/usr/lib/python2.7/site-packages/vagrantplaybook/ansible.py", line 6, in <module>
    from ansible.template import Templar
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 47, in <module>
    from ansible.vars.unsafe_proxy import UnsafeProxy, wrap_var
  File "/usr/lib/python2.7/site-packages/ansible/vars/__init__.py", line 42, in <module>
    from ansible.template import Templar
ImportError: cannot import name Templar
```

**Comment by rabin-io** [comment]
Hi @fabriziopandini is there any other why I can help to debug this problem ?

**Comment by fabriziopandini** [comment]
Discussion moved to https://github.com/fabriziopandini/vagrant-playbook/issues/9

**Comment by fabriziopandini** [comment]
@rabin-io can we consider closed this issue now?

**Comment by rabin-io** [comment]
Yes sorry about that, I'm using the plugin for the past 2 weeks, and it's working properly.
thanks.

**Comment by fabriziopandini** [comment]
Thanks for contributing!☺️
